version: '3.1'
services:
  jenkins:
    build: ./jenkins/master
    image: jenkins-jb/master:1.0
    container_name: jenkins
#    ports:
#      - "8080:8080"
    networks:
      - jb
  jenkins-slave:
    build: ./jenkins/slave
    image: jenkins-jb/slave:1.0
    container_name: jenkins-slave
    restart: always
    environment:
      - 'JENKINS_URL=http://jenkins:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Expose the docker daemon in the container
      - ./volume:/home/jenkins # Avoid mysql volume mount issue
    networks:
      - jb
    depends_on:
      - jenkins

  sonarqube:
    image: sonarqube
    container_name: sonarqube
    restart: unless-stopped
    ports:
      - 0.0.0.0:9000:9000
      - 0.0.0.0:9092:9092
    networks:
      - jb
  nexus:
    image: sonatype/nexus3
    restart: unless-stopped
    container_name: nexus
    volumes:
      - ./volume/nexus/data:/nexus-data
    environment:
      - NEXUS_CONTEXT=nexus
    user: root
    networks:
      - jb

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "443:443"
      - "80:80"
      - "5000:5000"
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf:ro
      - ./etc/nginx/proxy-settings.conf:/etc/nginx/conf.d/proxy-settings.conf:ro
      - ./etc/nginx/options-ssl-nginx.conf:/etc/certificates/options-ssl-nginx.conf:ro
      - /home/leonid/devopsstudy.nip.io.crt:/etc/certificates/devopsstudy.nip.io.crt:ro
      - /home/leonid/devopsstudy.nip.io:/etc/certificates/devopsstudy.nip.io:ro
    restart: unless-stopped
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
      - jb

networks:
  jb:
