apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gustbook
spec:
  destination:
    name: 'name'
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: guestbook
    repoURL: 'https://github.com/argoproj/argocd-example-apps'
    targetRevision: HEAD
  project: default
