apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-certificate
spec:
  secretName: hello-deployment-tls-ca-key-pair
  dnsNames:
    - "*.hsh.com"
    - "*"
  isCA: true
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer